### ISSUE TITLE
Database Exception: SQLSTATE

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/Workflow#126]
**Description**

````Database Exception: SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied: "RI_ConstraintTrigger_c_423079" is a system trigger
The SQL being executed was: ALTER TABLE public."workflow_submissions" DISABLE TRIGGER ALL;

Migration: verbb\workflow\migrations\m190713_000000_fixDraftForeignKey

Output:

> execute SQL: ALTER TABLE public.{{%workflow_submissions}} DISABLE TRIGGER ALL; ...Exception: SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied: "RI_ConstraintTrigger_c_423079" is a system trigger
The SQL being executed was: ALTER TABLE public."workflow_submissions" DISABLE TRIGGER ALL; (/home/forge/redacted/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /home/forge/redacted/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE pub...')
#1 /home/forge/redacted/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE pub...')
#2 /home/forge/redacted/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /home/forge/redacted/vendor/verbb/workflow/src/migrations/m190713_000000_fixDraftForeignKey.php(17): yii\db\Migration->execute('ALTER TABLE pub...')
#4 /home/forge/redacted/vendor/craftcms/cms/src/db/Migration.php(52): verbb\workflow\migrations\m190713_000000_fixDraftForeignKey->safeUp()
#5 /home/forge/redacted/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /home/forge/redacted/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(verbb\workflow\migrations\m190713_000000_fixDraftForeignKey))
#7 /home/forge/redacted/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#8 /home/forge/redacted/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#9 /home/forge/redacted/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /home/forge/redacted/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/forge/redacted/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /home/forge/redacted/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#14 /home/forge/redacted/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /home/forge/redacted/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#16 /home/forge/redacted/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#17 /home/forge/redacted/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /home/forge/redacted/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/forge/redacted/web/index.php(21): yii\base\Application->run()
#20 {main}````


**Steps to reproduce**
1. Upgrade plugin
2.

**Additional info**
- Plugin version: 1.5.4
- Craft version: 3.4.29.1
- Multi-site: Yes

**Additional context**

**Comment by theskyfloor** [comment]
PostgresSQL

**Comment by engram-design** [comment]
What version of Craft and Workflow are you updating from? What version on Postgres are you using? Just did a quick update from Workflow 1.2.0 and didn't seem to throw issues.
