### ISSUE TITLE
Error "Undefined variable $currentSite" after update to 1.7.1

### ISSUE THREAD

**Issue by michaelhue** [engram-design/Workflow#144]
**Description**
I received a bug report from a client after updating Workflow to v1.7.1.
Trying to publish a submission in the control panel results in a server error.

```
yii\base\ErrorException: Undefined variable $currentSite
#9 /var/www/virtual/atlasnds/app/vendor/verbb/workflow/src/controllers/SubmissionsController.php(65): yii\base\ErrorHandler::handleError
#8 /var/www/virtual/atlasnds/app/vendor/craftcms/cms/src/web/ErrorHandler.php(84): craft\web\ErrorHandler::handleError
#7 /var/www/virtual/atlasnds/app/vendor/verbb/workflow/src/controllers/SubmissionsController.php(65): verbb\workflow\controllers\SubmissionsController::beforeAction
#6 /var/www/virtual/atlasnds/app/vendor/yiisoft/yii2/base/Controller.php(176): yii\base\Controller::runAction
#5 /var/www/virtual/atlasnds/app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /var/www/virtual/atlasnds/app/vendor/craftcms/cms/src/web/Application.php(293): craft\web\Application::runAction
#3 /var/www/virtual/atlasnds/app/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application::_processActionRequest
#2 /var/www/virtual/atlasnds/app/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application::handleRequest
#1 /var/www/virtual/atlasnds/app/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(26): null
```

**Steps to reproduce**
1. Publish a submission

**Additional info**
- Plugin version: 1.7.1
- Craft version: 3.7.37
- Multi-site: No

**Additional context**
<img width="983" alt="Bildschirmfoto 2022-03-22 um 12 49 30" src="https://user-images.githubusercontent.com/31861/159475522-5cd07392-b798-4597-86ce-3cbd8206888e.png">

**Comment by engram-design** [comment]
Should be fixed in [1.7.2](https://github.com/verbb/workflow/releases/tag/1.7.2)
