### ISSUE TITLE
Warnings and errors when clicking through control panel

### ISSUE THREAD

**Issue by tremby** [engram-design/Workflow#146]
**Description**

I was exploring why Craft's log files are so noisy, and noticed that Workflow is emitting some warnings and errors.

Relevant part of logs:
```
==> storage/logs/phperrors.log <==
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Undefined variable $context in /srv/my-project/vendor/verbb/workflow/src/services/Service.php on line 213
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type null in /srv/my-project/vendor/verbb/workflow/src/services/Service.php on line 213
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Attempt to read property "uid" on null in /srv/my-project/vendor/verbb/workflow/src/models/Settings.php on line 38
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Undefined variable $context in /srv/my-project/vendor/verbb/workflow/src/services/Service.php on line 214
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type null in /srv/my-project/vendor/verbb/workflow/src/services/Service.php on line 214
[12-Apr-2022 11:15:52 America/Los_Angeles] PHP Warning:  Attempt to read property "uid" on null in /srv/my-project/vendor/verbb/workflow/src/models/Settings.php on line 87

==> storage/logs/web-2022-04-12.log <==
[2022-04-12T18:15:52.183314+00:00] web.ERROR: yii\base\ErrorException: Undefined variable $context in /srv/my-project/vendor/verbb/workflow/src/services/Service.php:213
Stack trace:
#0 /srv/my-project/vendor/craftcms/cms/src/web/ErrorHandler.php(77): yii\base\ErrorHandler->handleError(2, 'Undefined varia...', '/srv/my-project...', 213)
#1 /srv/my-project/vendor/verbb/workflow/src/services/Service.php(213): craft\web\ErrorHandler->handleError(2, 'Undefined varia...', '/srv/my-project...', 213)
#2 [internal function]: verbb\workflow\services\Service->renderEntrySidebar(Object(craft\events\DefineHtmlEvent))
#3 /srv/my-project/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DefineHtmlEvent))
#4 /srv/my-project/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\elements\\...', 'defineSidebarHt...', Object(craft\events\DefineHtmlEvent))
#5 /srv/my-project/vendor/craftcms/cms/src/base/Element.php(4247): yii\base\Component->trigger('defineSidebarHt...', Object(craft\events\DefineHtmlEvent))
#6 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementsController.php(779): craft\base\Element->getSidebarHtml(false)
#7 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementsController.php(395): craft\controllers\ElementsController->_editorSidebar(Object(craft\elements\Entry), false, true)
#8 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementsController.php(717): craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\models\FieldLayoutForm))
#9 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementsController.php(419): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Entry), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#10 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#11 /srv/my-project/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(107): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#12 /srv/my-project/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#13 /srv/my-project/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#14 /srv/my-project/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#15 /srv/my-project/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#16 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#17 /srv/my-project/web/index.php(12): yii\base\Application->run()

```

**Steps to reproduce**
1. From the control panel, click to make a new entry, eg entries -> pages -> new entry
2. For this set of logs, I might have then clicked back to the "pages" page, I'm not certain
3. See logs

**Additional info**
- Plugin version: craft-4 at 90606a4
- Craft version: 4.0.x-dev at 3fa417b
- Multi-site: Yes

**Additional context**
Headless mode is on.

Other plugins:
- Control Panel CSS v2.x-dev
- Formie dev-craft-4
- Navigation dev-craft-4
- Redactor 3.0.0-beta.2
- Retour 4.0.0-beta.4
- SEOmatic 4.0.0-beta.7
- Typed link field 2.1.0-rc
- Vizy dev-craft-4

**Comment by engram-design** [comment]
Should be fixed in [2.0.0-beta.2](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.2)
