### ISSUE TITLE
Save draft and submit for review returns Internal Server Error

### ISSUE THREAD

**Issue by rossnorthrup** [engram-design/Workflow#196]
### Describe the bug

Workflow version: 1.5.7

When I login in and open a page and all the most recent revision content is there, on the Current page, I do not have to go up and choose the latest revision to see the content.

I make an edit.

I choose, in the upper right hand corner: “Create a Draft”. It now says: “Draft 1”, in the top grey tab where it used to say “Current”.

When I try to choose: “Save draft and submit for review”, I get an Internal Server error.

### Steps to reproduce

1. Open an unpublished entry
2. Save draft and submit for review

### Craft CMS version

3.9.3

### Plugin version

1.5.7

### Multi-site?

no

### Additional context

Editor User Permissions - 
<img width="390" alt="image" src="https://github.com/verbb/workflow/assets/72947606/c62fe397-3af4-4603-a0a8-032fac4bf67a">

Workflow General Settings - 
<img width="784" alt="image" src="https://github.com/verbb/workflow/assets/72947606/6d67ce9a-b76a-402f-aab6-355b3c2443bc">

Workflow Notifications Settings - 
<img width="810" alt="image" src="https://github.com/verbb/workflow/assets/72947606/7b30bdf6-a859-45d3-bf35-1f00f4893ac5">

PHP error - 
[error] TypeError: TypeError: craft\web\Controller::_enforceAllowAnonymous(): Argument #1 ($action) must be of type yii\base\Action, string given, called in /var/www/html/vendor/craftcms/cms/src/web/Controller.php on line 137 and defined in /var/www/html/vendor/craftcms/cms/src/web/Controller.php:142
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(137): craft\web\Controller->_enforceAllowAnonymous('save-submission')
#1 /var/www/html/vendor/verbb/workflow/src/controllers/SubmissionsController.php(61): craft\web\Controller->beforeAction('save-submission')
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(176): verbb\workflow\controllers\SubmissionsController->beforeAction('save-submission')
#3 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-draft', Array)
#4 /var/www/html/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('workflow/submis...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(608): craft\web\Application->runAction('workflow/submis...', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/web/index.php(21): yii\base\Application->run()
#9 {main}

**Comment by engram-design** [comment]
Workflow 1.5.7 is a bit out of date now (3 years old), can you try on the latest version?
